.gitignore, docker-compose.yaml, job_handlers/reverse_description/__init__.py, package.json, src/plugins/demo-app/App.tsx, src/plugins/demo-app/Routes.tsx, src/plugins/demo-app/layout/Content.tsx, src/plugins/demo-app/layout/Menu.tsx, src/plugins/demo-app/pages/JobExample.tsx
- Adds a demo job handler plugin
- Adds some demo job control code for frontend
part of #10
=> feature: add example for job plugin and job usage

src/plugins/demo-app/App.tsx, src/plugins/demo-app/Routes.tsx
=> fix: update routing setup for demo-app

bin/cli.js
use regex to sanitize repo name variable in CLI
closes #18
=> fix: sanitize repo name variable in cli.js

app/data/DemoApplicationDataSource/instances/demoApplication.json, app/data/DemoApplicationDataSource/instances/package.json, app/data/DemoApplicationDataSource/models/CarPackage/Car.json, app/data/DemoApplicationDataSource/models/CarPackage/Wheel.json, app/data/DemoApplicationDataSource/models/DemoApplication.json, app/data/DemoApplicationDataSource/models/package.json, job_handlers/reverse_description/__init__.py, package.json, src/App.tsx, src/plugins/demo-app/App.tsx, src/plugins/demo-app/Routes.tsx, src/plugins/demo-app/Types.ts, src/plugins/demo-app/index.tsx, src/plugins/demo-app/layout/Content.tsx, src/plugins/demo-app/pages/BlueprintInteraction.tsx, src/plugins/demo-app/pages/JobExample.tsx, src/plugins/demo-app/pages/Overview.tsx, yarn.lock
update for breaking changes to type syntax and some DMSS endpoints
=> chore: update with new type syntax

src/plugins/demo-app/index.tsx
=> chore: add types to exported plugins

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/code-maintenance.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/pull_request_template.md
* Add pull request template
* Add issue templates
* Make consistent pull requests and issues format
=> chore: add pull request and issue templates

app/data/DemoApplicationDataSource/instances/package.json, app/data/DemoApplicationDataSource/models/package.json, job_handlers/reverse_description/__init__.py, package.json, src/plugins/demo-app/pages/JobExample.tsx, yarn.lock
https://github.com/equinor/data-modelling-storage-service/issues/276
=> refactor: replace sys:// with dmss://

.github/CODEOWNERS, README.md, app/data/DemoApplicationDataSource/instances/demoApplication.json, app/data/DemoApplicationDataSource/instances/recipe_links/demoApp.json, app/data/DemoApplicationDataSource/models/CarPackage/Car.json, app/data/DemoApplicationDataSource/models/CarPackage/Wheel.json, app/data/DemoApplicationDataSource/models/DemoApplication.json, package.json, src/plugins/demo-app/pages/BlueprintInteraction.tsx, yarn.lock
- Update the demo-app to use a lookup for uiRecipes
- Add a section on uiPlugins in README
The demo-app should have an example on how to create and use recipe lookups
closes #37
=> feature: create recipe lookup for demo-app

job_handlers/reverse_description/__init__.py, package.json, yarn.lock
updtae dm core package
dmss api has been updated
https://github.com/equinor/data-modelling-storage-service/issues/324
=> chore: update dm-core version and formatting

package.json, src/plugins/demo-app/pages/BlueprintInteraction.tsx, yarn.lock
update NewEntityButton props due to change in dm-core
update
https://github.com/equinor/dm-core-packages/issues/40
=> chore: update NewEntityButtonProps and dm-core version

src/plugins/demo-app/layout/Header.tsx
=> refactor: remove dmt from about

docker-compose.yaml, package.json, src/plugins.js, src/plugins/demo-app/Routes.tsx, src/plugins/demo-app/layout/Menu.tsx, src/plugins/demo-app/pages/BlueprintInteraction.tsx, src/plugins/demo-app/pages/Browse.tsx, src/plugins/demo-app/pages/Overview.tsx, yarn.lock
=> feature: rework overview to browse

src/plugins/demo-app/design/Icons.ts, src/plugins/demo-app/design/styles.ts, src/plugins/demo-app/layout/Menu.tsx, src/plugins/demo-app/pages/BlueprintInteraction.tsx, src/plugins/demo-app/pages/JobExample.tsx
=> fix: add menu icons

README.md
add more details to README how to run the app locally.
closes #53
=> docs: add more details on how to run app

.env, docker-compose.yaml
- Adds .env file for controlling image tags
closes #55
=> feature: add .env file for container versions

.github/workflows/on-schedule-daily.yaml
Adds a daily test of whether create-dm-app is working when run with standard parameters
Tests are nice
Refs #38
=> ci: nightly test

.gitignore, package-lock.json, package.json, src/plugins.js, src/plugins/demo-app/index.tsx
* Add form plugin
* Make it possible to view and edit documents
=> feat: add form plugin

package-lock.json, package.json
Updates dependency to the package dm-core-plugins instead of separate plugins. 
#77
=> Fix/ You're stuck in the past. Depend on a newer version of me bro. 

.env, src/index.tsx
* Add support to specify Azure as an authentication provider (OAauth)
* This is needed in production, where the backend needs to have auth enabled
=> feat: add oauth auth support

.env, package.json, src/index.tsx
* Add DMSS URL to `.env` file, so that it is easier to change
> **NOTE**: Should also do this for the job, but need to add some code in dm-core to handle it first (similar to dmss use context or something so that it is possible to pass it inn from index.tsx).
=> refactor: make it easier to change dmss url

.github/workflows/healthcheck.yaml, .github/workflows/on-schedule-nightly.yaml, .github/workflows/tests.yaml, README.md, vite.config.ts
- Fixed bug in healthcheck
- Originally, it was only run nightly and tested the code on npmjs. I adapted it so it can run on push with the code in repo, thus avoiding bugs to happen.
The healthcheck was failing
#77
=> ci: make healthcheck pass

README.md, reset-app.sh
=> docs: update readme

src/App.tsx
=> style: import css from dm-core

app/data/DemoDS/DemoApplication/recipes/demoApp.json, docker-compose.yaml
=> fix: reorder app header plugins
